### ISSUE TITLE
Or not working as expected

### ISSUE THREAD

**Issue by LittleHelicase** [jneen/parsimmon#48] opened 2015-10-16 22:35 UTC
Hello,

I just tried Parsimmon and somehow "or" does not always what I believe it should do. Here is a small example

```js
var plus = Parsimmon.string("+")
var word = Parsimmon.string("a")
var operation = Parsimmon.seq(word, plus)
var term = word.or(operation)

console.log(operation.parse("a+")) // status: true
console.log(word.parse("a+"))  // status: false
console.log(term.parse("a+")) // status: false
```

The operation can parse "a+" but word.or(operation) cannot. The or function works with simple strings. I think it does not work due to the `seq` in the or statement. The expression `operation.or(word)` works fine, but I need it in this order for my complex example. Am I using it wrong?

**Comment by wavebeem** [comment] 2015-10-17 20:25
@LittleHelicase The order matters on `.or`. You're trying to match `word` or `word plus`, but you try just `word` first. That parser succeeds, so it never goes into the `.or` argument. Then it has extra characters left over (`"+"`), and fails because there is no parser left to want characters.

If two parser paths have the same beginning, the longer path needs to come first.

**Comment by wavebeem** [comment] 2016-04-29 17:27
Closing this since Parsimmon is working as designed in this situation.

**Closed by wavebeem** 2016-04-29 17:27 UTC
