### ISSUE TITLE
p.or and p.alt wont backtrack

### ISSUE THREAD

**Issue by oleander** [jneen/parsimmon#97] opened 2016-07-24 19:49 UTC
I've these two examples which fails

``` javascript
// Input
var input = "hello hello";

//  Parser
var hello = p.string("hello");
var hellos = p.sepBy(hello, p.whitespace);

// Examples
console.info(p.alt(hello, hellos).parse(input));
console.info(hello.or(hellos).parse(input));

// Output
{ status: false,
  index: { offset: 5, line: 1, column: 6 },
  expected: [ 'EOF' ] }
{ status: false,
  index: { offset: 5, line: 1, column: 6 },
  expected: [ 'EOF' ] }
```

I was expecting both to try the first parser `hello` and on failure backtrack and continue with `hellos`. How come this isn't possible and how would I solve this without having to reimplement the different parsers? 

Real world use case: In my application I've have created different isolated parsers which initially overlap. Here is some example input (`:highlights` in vim):

``` javascript
var example1 = "SpellLocal     xxx ctermbg=14 gui=undercurl"
var example2 = "rubyEval       xxx links to Statement"
var example3 = "rubyKeywordAsMethod xxx cleared"
```

Each line represents a different parser, but happens to look the same in the beginning. Each example have it's own parser. A line can only be mapped to one parser. I was hoping to do something like below as this would allow me keep the parsers independent. 

``` javascript
var input = [example1, example2, example3].sample();
exampleParser1.or(exampleParser2).or(exampleParser3).parse(input)
```

**Comment by wavebeem** [comment] 2016-07-25 01:27
Just so you know, `x.or(y)` is just defined as `P.alt(x, y)`, so the results of those should never be different. 

The error in your parser is that you need to put the **longer** of two parsers first when they start with the same prefix.

The documentation gives [an example of this limitation and how to work around it](https://github.com/jneen/parsimmon/blob/master/API.md#parsimmonaltp1-p2-pn).

**Comment by oleander** [comment] 2016-07-25 14:53
Hi and thanks for your quick answer! I looked at the docs before I posted but wasn't sure and here's why. 

The docs states the following:

> Accepts any number of **parsers**, yielding the value of the **first** one that succeeds, **backtracking** in between. 

It continues saying:

> This means that the order of parsers matters. If two parsers match the same prefix, the longer of the two must come first.

The first sentence doesn't imply the later as such an implementation would be [commutative](https://en.wikipedia.org/wiki/Commutative_property) – which isn't the case. It would be like saying; *my name is Linus, therefore I like ice cream*. I do like ice cream, but it has nothing to do with my name :) 

The current implementation only seams backtracks if the parser hasn't consumed anything yet – which is almost never the case for complex parsers passed to `alt`. Looking at the implementation the call to `mergeReplies` results in this behaviour.

``` javascript
for (var j = 0; j < parsers.length; j += 1) {
  result = mergeReplies(parsers[j]._(stream, i), result);
  if (result.status) return result;
}
```

I would like it to work like this:

``` javascript
for (var j = 0; j < parsers.length; j += 1) {
  result = parsers[j]._(stream, i);
  if (result.status) return result;
}
```

Is there a reason for this behaviour? I might have missed something, which is why I'm asking. Rewrote my current implementation to fit the API which actually reduce the number of lines – which makes me believe I'm the one doing something wrong.

Awesome tool btw!

**Comment by oleander** [comment] 2016-07-25 15:01
I took a look at the [Parsec docs](https://hackage.haskell.org/package/parsec-3.1.11/docs/Text-Parsec-Combinator.html) (which this lib seams to based on). They didn't have a `any` function, but they do have `choice` which states the following.

> `choice :: Stream s m t => [ParsecT s u m a] -> ParsecT s u m a`
choice `ps` tries to apply the parsers in the list `ps` in order, until one of them succeeds. Returns the value of the succeeding parser.

This is how I would expect `alt` to work.

**Comment by wavebeem** [comment] 2016-07-25 15:48
All the mergeReplies function does is combine multiple failed parses for better error messages. Can you give me a full example of the parser that failed when you expected it to work?

Even if the problem is potentially "on your end", I would like to know more since this function results in a lot of open issues, so I would like to continue to improve the documentation.

As for the library, you mostly have jneen to thank for it, I'm just the new maintainer 👈

**Comment by wavebeem** [comment] 2016-07-29 00:24
Anything else you can add, @oleander?

**Comment by wavebeem** [comment] 2016-08-04 14:45
I'm closing this due to inactivity. Please reply if it's still a problem.

**Comment by oleander** [comment] 2016-08-04 14:48
Sorry for the delay.

Not sure what more to add. Fixing the inconsistency in the docs and implementing a commutative `or` function would fix it.

**Comment by oleander** [comment] 2016-08-04 14:51
Are the streams and parsers mutable?

**Comment by wavebeem** [comment] 2016-08-04 14:52
The "stream" is just a JavaScript string, so it's immutable. Parsers are not frozen JS objects, but they aren't expected to be mutated.

Per the docs:

> Accepts any number of parsers, yielding the value of the *first one that succeeds*, backtracking in between

That seems to imply the order matters, meaning it's not commutative. Is there a different way I could document `P.alt` that would make that more clear?

**Comment by oleander** [comment] 2016-08-04 15:07
That's the problem then I guess. I would assume that the parse tree is immutable and that a change creates a new tree – not alters it. 

I would rename the `alt` and `or` as they really don't do what one would expect. I would also remove the word `backtrack` as it's more of a `continue`.  Currently it tries the first arg to `alt`, if it fails it continues from this altered stage to the next argument and so on.

I suggest using something like [immutable js](https://facebook.github.io/immutable-js/) to implement an immutable parse tree.

**Comment by wavebeem** [comment] 2016-08-04 15:33
The primary reason I closed this issue earlier is I did not see a demonstration of how `P.alt` fails to backtrack. If you look at the source code, you can see the value of `i`, the index to start parsing at, does *not* change between parse attempts for the arguments of `P.alt`. This means it starts parsing at the same point after each failed parse --- thus it "backtracks". Nothing is being mutated here.

If you have an example showing how it doesn't seem to backtrack, I'm happy to take a look at it.

```javascript
  var alt = Parsimmon.alt = function() {
    var parsers = [].slice.call(arguments);
    var numParsers = parsers.length;
    if (numParsers === 0) return fail('zero alternates')

    for (var j = 0; j < numParsers; j += 1) {
      assertParser(parsers[j]);
    }

    return Parser(function(stream, i) {
      var result;
      for (var j = 0; j < parsers.length; j += 1) {
        result = mergeReplies(parsers[j]._(stream, i), result);
        if (result.status) return result;
      }
      return result;
    });
  };
```

**Comment by oleander** [comment] 2016-08-04 15:51
Take a look at the example I posted in my first post.

**Comment by oleander** [comment] 2016-08-04 16:10
The source even symlinks `or` to `concat` (`_.concat = _.or;`).  How come `return a + b` is considered the same as`return a || b`?

**Comment by wavebeem** [comment] 2016-08-04 16:34
I did read your example from the first post. The problem there was that the order *does* matter.

You also posted a partial example of some kind of vim config parser, but there wasn't enough there for me to read into.

`_.concat` is there for fantasyland compatibility. And `x.or(y)` is just shorthand for `P.alt(x, y)`.

**Comment by wavebeem** [comment] 2016-08-04 16:35
Those methods are unrelated to the JS operators `+` and `||`.

**Comment by oleander** [comment] 2016-08-04 16:46
I don't think I can add more to the discussion. Feel free to close the issue if you consider it solved.

**Closed** 2016-08-04 18:26 UTC

**Comment by jneen** [comment] 2016-08-06 01:36
Hi @oleander.  The docs are correct, and the example you gave is behaving according to the docs. An `alt` parser tries its alternatives *in order*, and backtracks *only when they fail*. If a parser succeeds along the way, that's it, the `alt` has succeeded, and the parse moves on. In the example, `hello` succeeded, but the overall parse failed because it was looking for an EOF (we actually use `.skip(eof)` on your parser to ensure that there

**Comment by jneen** [comment] 2016-08-06 01:37
And yes, the language "yields the *first* one that succeeds" does in fact imply that order matters - it tries them in order, and stops as soon as one succeeds.

**Comment by jneen** [comment] 2016-08-06 01:39
Alternation in parser combinators is not generally commutative - the only requirement is that it's *associative* - `alt(a, alt(b, c)) == alt(alt(a, b), c)`, which it is in this case. Parsec's alternation (the `<|>` operator, or the `choice` function) is also not commutative.
